# Basic Information
title: Hua Chang Bakker
position: Graduate Student
affiliation: University of Amsterdam
email: hua.chang.bakker (at) student.uva.nl

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: Hua Chang Bakker, hua chang bakker, huachang bakker, researcher, machine learning, deep learning
description: Academic personal homepage of Hua Chang Bakker..
canonical: https://minimal-light-theme.yliu.me/

# Links
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?user=cxOetXkAAAAJ
# cv_link: assets/files/curriculum_vitae.pdf
github_link: https://github.com/huachangb
linkedin: https://www.linkedin.com/in/hua-chang-bakker/

# Images (e.g., your profile picture and your website's favicon)
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively.
avatar: ./assets/img/avatar.png
# favicon: PATH TO FAVICON
# favicon_dark: PATH TO FAVICON

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: true

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: true

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Serif" # or "Sans Serif"

# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
